DROP TABLE IF EXISTS category,compilation,event,users,request,events_compilations;
CREATE TABLE IF NOT EXISTS category
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT pk_user PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS event
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation        VARCHAR(255)                            NOT NULL,
    category_id       BIGINT REFERENCES category (id),
    confirmedRequests INT    DEFAULT 0,
    createdOn         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    eventDate         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator         BIGINT REFERENCES users (id),
    location_lat      FLOAT                                   NOT NULL,
    location_lon      FLOAT                                   NOT NULL,
    paid              BOOLEAN                                 NOT NULL,
    participantLimit  BIGINT                                  NOT NULL,
    publishedOn       TIMESTAMP WITH TIME ZONE                NOT NULL,
    requestModeration BOOLEAN                                 NOT NULL,
    state             VARCHAR(10)                             NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    views             BIGINT DEFAULT 0,
    CONSTRAINT pk_event PRIMARY KEY (id)

);
CREATE TABLE IF NOT EXISTS request
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created  VARCHAR(255)                            NOT NULL,
    event_id BIGINT REFERENCES event (id),
    user_id  BIGINT REFERENCES users (id),
    status   VARCHAR(20),
    CONSTRAINT pk_request PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT REFERENCES event (id),
    compilation_id BIGINT REFERENCES compilation (id),
    PRIMARY KEY (event_id, compilation_id)
);
